### ISSUE TITLE
Cap Max Return Count to 200

### ISSUE THREAD

**Issue by Mosely** [Mosely/fss#15]
Some endpoints try to return 100,000+ records, exceeding memory allocation, so go ahead an cap the max return record count to 200.  This'll be adjusted on a per endpoint basis as needed.

**Comment by Mosely** [comment]
See https://laravel.com/docs/5.5/queries#ordering-grouping-limit-and-offset , specifically the part talking about the limit method.

**Comment by mlhomfeld** [comment]
Ran through the controllers and added limit(200). Will attempt testing after 6pm. Please review at your convenience.

**Comment by Mosely** [comment]
Looks good.
