### ISSUE TITLE
Make All Model and Controller Classes Adhere to PSR

### ISSUE THREAD

**Issue by Mosely** [Mosely/fss#16]
Need to remove underscores in file and class names, and use pascal naming case.  Also, remember to fix the use statements to reflect this as well as all references in routes.php and controllers.php.

Now, who wants to tackle this?

**Comment by bjbrookz** [comment]
I can take a shot… quick look shows that routes.php is already using the convention?

**Comment by Mosely** [comment]
It does for the most part.  There's a few references that still have
underscores.

**Comment by bjbrookz** [comment]
Here’s a dumb question… Is there a secret to renaming files? I’m attempting to rename the file via menu, Refractor, Rename but can’t get past the Preview of the changes. Error log is only giving me a generic “Internal Error.”

**Comment by Mosely** [comment]
Hmm, trying pulling down changes, first, and then try refactoring.

Dewayne

**Comment by bjbrookz** [comment]
No dice… I don’t see any commits coming when pulling down changes. Seems to indicate I’m current – menu, Team, Fetch from Upstream, view what’s coming, Ok. Then menu, Team, Merge. Any steps I’m missing or out of order that could prevent me from changing it that you can see?

**Comment by Mosely** [comment]
Are you pulling down the dev branch or the master branch?

**Comment by bjbrookz** [comment]
Dev. I’m afraid to touch master :)

**Comment by Mosely** [comment]
I remember reading somewhere that Eclipse has trouble renaming stuff when
there's any errors in the project.  If there are any errors (which could be
due to Composer not pulling down all of the dependencies), correct them and
maybe Eclipse will then cooperate.

If anything, there's alway the Github web interface that you can use for
this completing this issue.

**Comment by bjbrookz** [comment]
Sounds like a plan

**Comment by bjbrookz** [comment]
Think we can mark this one complete…

**Comment by Mosely** [comment]
Looks good. Closing.
