### ISSUE TITLE
Implement Remaining Controllers

### ISSUE THREAD

**Issue by Mosely** [Mosely/fss#2]
The rest of the controllers are needed in order to expose the remaining http endpoints.

**Comment by Mosely** [comment]
The models are now in place, so controller development can now take place.

**Comment by mlhomfeld** [comment]
I'm not sure I fully understand which controllers need to be implemented and/or developed.

**Comment by Mosely** [comment]
No worries.  For an example, take a look at the addressController.php.
Follow its code.  You'll be building a controller for pretty much every
model.

Have a go with making a controller for the gender model, using
addressController.php as a guide.

**Comment by mlhomfeld** [comment]
The remaining controllers have been implemented in the dev branch for review.

**Comment by Mosely** [comment]
Controllers and models are in place.  Moving out of Alpha.

**Comment by bjbrookz** [comment]
Nice work, thanks.
